RideSharingAPP.WEB/RideSharingAPP.WEB/Controllers/ClientController.cs
using RideSharingApp.BLL.Interfaces;
using RideSharingApp.BLL.Services;
using RideSharingAPP.BLL.DTO.AccountInformationDTO;
using RideSharingAPP.BLL.DTO.CarDTO;
using RideSharingAPP.BLL.DTO.ClientDTO;
using RideSharingAPP.BLL.DTO.CompanionDTO;
using RideSharingAPP.BLL.DTO.DriverDTO;
using RideSharingAPP.BLL.DTO.TripDTO;
using RideSharingAPP.BLL.Interfaces;
using RideSharingAPP.BLL.Interfaces.IValidations;
using RideSharingAPP.WEB.Attributes;
using RideSharingAPP.WEB.Models.Authorization;
using RideSharingAPP.WEB.Models.Car;
using RideSharingAPP.WEB.Models.Client;
using RideSharingAPP.WEB.Models.Companion;
using RideSharingAPP.WEB.Models.Driver;
using RideSharingAPP.WEB.Models.PassingPoint;
using RideSharingAPP.WEB.Models.Route;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace RideSharingAPP.WEB.Controllers
{
    /// <summary>The controller in which all actions will be carried out by the passenger.</summary>
    public class ClientController : Controller
    {
        IAccountInformationValidation accountInformationValidation;
        IClientValidation clientValidation;
        ITripValidation tripValidation;
        ICarValidation carValidation;
        IDriverValidation driverValidation;
        ICompanionValidation companionValidation;

        IAccountInformationService accountInformationService;
        ICompanionService companionService;
        IDriverService driverService;
        ICarService carService;
        ITripService tripService;
        IClientService clientService;

        /// <summary>Controller constructor.</summary>
        /// <value>Accepts the interface of the validation service as well as the service table of clients.</value>
        /// <remarks>Constructor - a function that fires before other constructor methods.</remarks>
        public ClientController(IClientService clientServ, IClientValidation clientValid, ITripValidation tripValid, ITripService tripServ,
            IDriverService driverServ, IDriverValidation driverValid, ICarService carServ, ICarValidation carValid, ICompanionService companionServ,
            ICompanionValidation companionValid, IAccountInformationService accountServ, IAccountInformationValidation accountVal)
        {
            carValidation = carValid;
            driverValidation = driverValid;
            clientValidation = clientValid;
            tripValidation = tripValid;
            companionValidation = companionValid;
            accountInformationValidation = accountVal;

            accountInformationService = accountServ;
            companionService = companionServ;
            driverService = driverServ;
            carService = carServ;
            tripService = tripServ;
            clientService = clientServ;
        }

        /// <summary>Sends data about a new user to the server</summary>
        /// <param name="client"> model containing data about a new user.</param>
        [Authorize(Roles = "Passenger"), ValidateAntiForgeryToken, HttpPost]
        public async Task<ActionResult> Create(ClientViewModel client)
        {
            var mappedClient = new AutoMap<ClientDTOCreate, ClientViewModel>().Initialize(client);
            var error = clientValidation.IsValid(mappedClient);
            if (error == null)
            {
                mappedClient.AccountInformationID = int.Parse(HttpContext.Request.Cookies["AccountInformationId"].Value);
                var newClientsId = await clientService.Create(mappedClient);
                return RedirectToAction("SearchRoute");
            }
            else
            {
                ModelState.AddModelError("", error.Message);
            }
            return View();
        }

        [Authorize(Roles = "Passenger"), HttpGet]
        public ActionResult ChangePassword()
        {
            return View();
        }

       
        [Authorize(Roles = "Passenger"), HttpPost, ValidateAntiForgeryToken]
        public async Task<ActionResult> ChangePassword(ChangePasswordViewModel account)
        {
            var mappedAccount = new AutoMap<AccountInformationDTOChangePassword, ChangePasswordViewModel>().Initialize(account);
            var error = accountInformationValidation.IsValidChangePassword(mappedAccount);
            if (error == null)
            {
                mappedAccount.AccountInformationId = Convert.ToInt32(HttpContext.Request.Cookies["AccountInformationId"].Value);
                var editAccountId = await accountInformationService.ChangePassword(mappedAccount);
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", error.Message);
            }
            return View(account);

        }

        [Authorize(Roles = "Passenger"), HttpGet]
        public async Task<ActionResult> Index()
        {
            var client = await clientService.FindAccount(Convert.ToInt32(HttpContext.Request.Cookies["AccountInformationId"].Value));
            var mappingClient = new AutoMap<ClientViewModel, ClientDTOCreate>().Initialize(client);
            ViewBag.PageTitle = "Данные о пользователе";
            return View(mappingClient);
        }

        /// <summary>Returns the form of creating a new client.</summary>
        /// <remarks>Displays a form for filling in data about a new user.</remarks>
        /// <returns>View()</returns>
        [Authorize(Roles = "Passenger"), HttpGet]
        public ActionResult Create()
        {
            ViewBag.PageTitle = "Личные данные";

            return View();
        }

        /// <summary>Checks for customer data in the database, if there is no data, sends it to the data filling form.</summary>
        /// <returns>View() or Redirect()</returns>
        [Authorize(Roles = "Passenger")]
        private async Task<int?> IsExistClientData()
        {
            string AccountInformationId = HttpContext.Request.Cookies["AccountInformationId"].Value;
            var userId = int.Parse(AccountInformationId);
            var passenger = await clientService.FindPassenger(userId);
            if (passenger == null)
            {
                return null;
            }
            return passenger.id;
        }

        [Authorize(Roles = "Passenger"), HttpGet]
        public async Task<ActionResult> SearchRoute()
        {
            var clientId = await IsExistClientData();
            if (clientId == null)
            {
                return RedirectToAction("Create");
            }

            ViewBag.PageTitle = "Поиск маршрута";
            return View();
        }

        [Authorize(Roles = "Passenger"), ValidateAntiForgeryToken, HttpPost]
        public async Task<ActionResult> SearchRoute(PointsViewModel route)
        {
            var clientId = await IsExistClientData();
            if (clientId == null)
            {
                return RedirectToAction("Create");
            }

            var mappingRoute = new AutoMap<TripDTOPoints, PointsViewModel>().Initialize(route);
            var error = tripValidation.PointsIsValid(mappingRoute);
            if (error == null)
            {
                return RedirectToAction("RoutesList", route);
            }
            else
            {
                ModelState.AddModelError("", error.Message);
            }
            ViewBag.PageTitle = "Поиск маршрута";
            return View();
        }

        [Authorize(Roles = "Passenger"), ValidateAntiForgeryToken, HttpPost, SetTempDataModelState]
        public async Task<ActionResult> RegisterForRoute(TripSearchedListViewModel tripInfo)
        {
            var clientId = await IsExistClientData();
            if (clientId == null)
            {
                return RedirectToAction("Create");
            }
            var error = await companionValidation.IsValid(Convert.ToInt32(clientId), tripInfo.id, int.Parse(HttpContext.Request.Cookies["AccountInformationId"].Value));
            if (error == null)
            {
                var companion = new CompanionDTOCreate
                {
                    TripID = tripInfo.id,
                    ClientID = Convert.ToInt32(clientId),
                    DateAndTimeOfArrival = tripInfo.DateAndTimeOfArrival,
                    DateAndTimeOfDepartue = tripInfo.DateAndTimeOfDepartue,
                    OriginCoordinates = tripInfo.OriginCoordinates,
                    EndCoordinates = tripInfo.EndCoordinates,
                    TotalCost = tripInfo.TotalСost
                };
                var newCompanionId = await companionService.RegistrationForTheRoute(companion);
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", error.Message);
            }
            ViewBag.PageTitle = "Поиск маршрута";
            return RedirectToAction("RegistrationRoutesList");
        }

        [Authorize(Roles = "Passenger"), HttpGet]
        public async Task<ActionResult> EditClient(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.PageTitle = "Изменение личных данных";

            string accountInformationId = HttpContext.Request.Cookies["AccountInformationId"].Value;
            var client = await clientService.Get(Convert.ToInt32(id));
            var mappedClient = new AutoMap<ClientViewModel, ClientDTOCreate>().Initialize(client);
            return View(mappedClient);
        }

        [Authorize(Roles = "Passenger"), ValidateAntiForgeryToken, HttpPost]
        public async Task<ActionResult> EditClient(ClientViewModel client)
        {
            var clientId = await IsExistClientData();
            if (clientId == null)
            {
                return RedirectToAction("Create");
            }

RideSharingAPP.WEB/RideSharingAPP.WEB/Views/Shared/_LayoutClient.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/jquery-3.3.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>


    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Main Styles -->
    <link rel="stylesheet" href="~/Content/Home/Css/style.min.css">

    <!-- Material Design Icon -->
    <link rel="stylesheet" href="~/Content/Home/Fonts/materialdesignicons.css">

    <!-- mCustomScrollbar -->
    <link rel="stylesheet" href="~/Content/Home/Css/jquery.mCustomScrollbar.min.css">

    <!-- Waves Effect -->
    <link rel="stylesheet" href="~/Content/Home/Css/waves.min.css">

    <!-- Sweet Alert -->
    <link rel="stylesheet" href="~/Content/Home/Css/sweetalert.css">

    <!-- Dark Themes -->
    <link rel="stylesheet" href="~/Content/Home/Css/style-dark.min.css">
</head>

<body>
    <div class="main-menu">
        <header class="header">
            <a href="" class="logo">RideSharing</a>
            <button type="button" class="button-close fa fa-times js__menu_close"></button>
        </header>
        <!-- /.header -->
        <div class="content">

            <div class="navigation">
                <ul class="menu js__accordion">
                    <li>
                        <a class="waves-effect parent-item js__control" href="#"><span>Маршруты</span><span class="menu-arrow fa fa-angle-down"></span></a>
                        <ul class="sub-menu js__content">
                            <li>@Html.ActionLink("Активные", "RegistrationRoutesList", "Client", null, "")</li>
                            <li>@Html.ActionLink("Найти", "SearchRoute", "Client", null, "")</li>
                        </ul>
                        <!-- /.sub-menu js__content -->
                    </li>
                </ul>
                <!-- /.menu js__accordion -->
            </div>
            <!-- /.navigation -->
        </div>
        <!-- /.content -->
    </div>
    <!-- /.main-menu -->

    <div id="mynavbar" class="fixed-navbar">
        <div class="pull-left">
            <button id="mobbutton" type="button" class="menu-mobile-button glyphicon glyphicon-menu-hamburger js__menu_mobile"></button>
            <h1 class="page-title">@ViewBag.PageTitle</h1>
            <!-- /.page-title -->
        </div>
        <!-- /.pull-left -->
        <div class="pull-right">
            <div class="ico-item">
                <a href="#" class="ico-item fa fa-search js__toggle_open" data-target="#searchform-header"></a>
                <form action="#" id="searchform-header" class="searchform js__toggle"><input type="search" placeholder="Search..." class="input-search"><button class="fa fa-search button-search" type="submit"></button></form>
                <!-- /.searchform -->
            </div>
            <!-- /.ico-item -->
            <div class="ico-item fa fa-arrows-alt js__full_screen"></div>
            <!-- /.ico-item -->
            <div class="ico-item">
                <img src="http://placehold.it/80x80" alt="" class="ico-img">
                <ul class="sub-ico-item">
                    <li>
                        @Html.ActionLink("Личный кабинет", "Index", "Client")
                    </li>
                    <li>
                        @Html.ActionLink("Выход", "LogOut", "Authorization")
                    </li>
                </ul>
                <!-- /.sub-ico-item -->
            </div>
            <!-- /.ico-item -->
        </div>
        <!-- /.pull-right -->
    </div>
    <!-- /.fixed-navbar -->

    <div id="wrapper">
        <div class="main-content">
            <div id="rendercontent" class="container body-content paddingform" style="margin: 0px 0px 0px 0px;">
                @RenderBody()
            </div>


            @Scripts.Render("~/bundles/jquery")
            @Scripts.Render("~/bundles/bootstrap")
            @RenderSection("scripts", required: false)
        </div>
        <!-- /.main-content -->
    </div><!--/#wrapper -->
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="assets/script/html5shiv.min.js"></script>
        <script src="assets/script/respond.min.js"></script>
    <![endif]-->
    <!--
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="~/Content/Home/Js/jquery.min.js"></script>
    <script src="~/Content/Home/Js/modernizr.min.js"></script>
    <script src="~/Content/Home/Js/bootstrap.min.js"></script>
    <script src="~/Content/Home/Js/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="~/Content/Home/Js/nprogress.js"></script>
    <script src="~/Content/Home/Js/sweetalert.min.js"></script>
    <script src="~/Content/Home/Js/waves.min.js"></script>
    <script src="~/Content/Home/Js/jquery.fullscreen-min.js"></script>
    <script src="~/Content/Home/Js/main.min.js"></script>

    <script type="text/javascript">
        if (!~navigator.userAgent.search('Windows')) {
            document.getElementById("mobbutton").disabled = false;
            document.getElementById("mobbutton").style.display = "block";
            document.getElementById("mynavbar").style.padding = "0px 20px 0px 70px";
        } else {
            document.getElementById("mynavbar").style.padding = "0px 20px 0px 20px";
            document.getElementById("mobbutton").disabled = true;
            document.getElementById("mobbutton").style.display = "none";
        }
    </script>
</body>
</html>

RideSharingAPP.WEB/RideSharingAPP.WEB/Views/Shared/_LayoutDriver.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/jquery-3.3.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>


    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Main Styles -->
    <link rel="stylesheet" href="~/Content/Home/Css/style.min.css">

    <!-- Material Design Icon -->
    <link rel="stylesheet" href="~/Content/Home/Fonts/materialdesignicons.css">

    <!-- mCustomScrollbar -->
    <link rel="stylesheet" href="~/Content/Home/Css/jquery.mCustomScrollbar.min.css">

    <!-- Waves Effect -->
    <link rel="stylesheet" href="~/Content/Home/Css/waves.min.css">

    <!-- Sweet Alert -->
    <link rel="stylesheet" href="~/Content/Home/Css/sweetalert.css">

    <!-- Dark Themes -->
    <link rel="stylesheet" href="~/Content/Home/Css/style-dark.min.css">
</head>

<body>
    <div class="main-menu">
        <header class="header">
            <a href="" class="logo">RideSharing</a>
            <button type="button" class="button-close fa fa-times js__menu_close"></button>
        </header>
        <!-- /.header -->
        <div class="content">

            <div class="navigation">
                <ul class="menu js__accordion">
                    <li>
                        <a class="waves-effect parent-item js__control" href="#"><span>Маршруты</span><span class="menu-arrow fa fa-angle-down"></span></a>
                        <ul class="sub-menu js__content">
                            <li>@Html.ActionLink("Активные", "RouteList", null, "")</li>
                            <li>@Html.ActionLink("Добавить", "CreateRoute", "Driver", null, "")</li>
                        </ul>
                        <!-- /.sub-menu js__content -->
                    </li>
                    <li>
                        <a class="waves-effect parent-item js__control" href="#">Автомобили<span class="menu-arrow fa fa-angle-down"></span></a>
                        <ul class="sub-menu js__content">
                            <li>@Html.ActionLink("Список", "CarList", null, "")</li>
                            <li>@Html.ActionLink("Добавить", "CreateCar", "Driver", null, "")</li>
                        </ul>
                        <!-- /.sub-menu js__content -->
                    </li>
                </ul>
                <!-- /.menu js__accordion -->
            </div>
            <!-- /.navigation -->
        </div>
        <!-- /.content -->
    </div>
    <!-- /.main-menu -->

    <div id="mynavbar" class="fixed-navbar">
        <div class="pull-left">
            <button id="mobbutton" type="button" class="menu-mobile-button glyphicon glyphicon-menu-hamburger js__menu_mobile"></button>
            <h1 class="page-title">@ViewBag.PageTitle</h1>
            <!-- /.page-title -->
        </div>
        <!-- /.pull-left -->
        <div class="pull-right">
            <div class="ico-item">
                <a href="#" class="ico-item fa fa-search js__toggle_open" data-target="#searchform-header"></a>
                <form action="#" id="searchform-header" class="searchform js__toggle"><input type="search" placeholder="Search..." class="input-search"><button class="fa fa-search button-search" type="submit"></button></form>
                <!-- /.searchform -->
            </div>
            <!-- /.ico-item -->
            <div class="ico-item fa fa-arrows-alt js__full_screen"></div>
            <!-- /.ico-item -->
            <div class="ico-item">
                <img src="http://placehold.it/80x80" alt="" class="ico-img">
                <ul class="sub-ico-item">
                    <li>
                        @Html.ActionLink("Личный кабинет", "Index", "Driver")
                    </li>
                    <li>
                        @Html.ActionLink("Выход", "LogOut", "Authorization")
                    </li>
                </ul>
                <!-- /.sub-ico-item -->
            </div>
            <!-- /.ico-item -->
        </div>
        <!-- /.pull-right -->
    </div>
    <!-- /.fixed-navbar -->

    <div id="wrapper">
        <div class="main-content">
            <div id="rendercontent" class="container body-content paddingform">
                @RenderBody()
            </div>


            @Scripts.Render("~/bundles/jquery")
            @Scripts.Render("~/bundles/bootstrap")
            @RenderSection("scripts", required: false)
        </div>
        <!-- /.main-content -->
    </div><!--/#wrapper -->
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="assets/script/html5shiv.min.js"></script>
        <script src="assets/script/respond.min.js"></script>
    <![endif]-->
    <!--
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="~/Content/Home/Js/jquery.min.js"></script>
    <script src="~/Content/Home/Js/modernizr.min.js"></script>
    <script src="~/Content/Home/Js/bootstrap.min.js"></script>
    <script src="~/Content/Home/Js/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="~/Content/Home/Js/nprogress.js"></script>
    <script src="~/Content/Home/Js/sweetalert.min.js"></script>
    <script src="~/Content/Home/Js/waves.min.js"></script>
    <script src="~/Content/Home/Js/jquery.fullscreen-min.js"></script>
    <script src="~/Content/Home/Js/main.min.js"></script>

    <script type="text/javascript">
        if (!~navigator.userAgent.search('Windows')) {
            document.getElementById("mobbutton").disabled = false;
            document.getElementById("mobbutton").style.display = "block";
            document.getElementById("mynavbar").style.padding = "0px 20px 0px 70px";
        } else {
            document.getElementById("mynavbar").style.padding = "0px 20px 0px 20px";
            document.getElementById("mobbutton").disabled = true;
            document.getElementById("mobbutton").style.display = "none";
        }
    </script>
</body>
</html>